apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  labels:
    io.kompose.service: db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: db
    spec:
      containers:
        - name: mariadb
          image: mariadb:11.8.5-ubi
          ports:
            - containerPort: 3306

          env:
            - name: MARIADB_DATABASE
              value: vehicles_db
            - name: MARIADB_USER
              value: appUser
            - name: MARIADB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-pwd
                  key: mariadb-pwd
            - name: MARIADB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-pwd
                  key: mariadb-pwd

          volumeMounts:
            - name: db-data
              mountPath: /var/lib/mysql
            - name: db-cm1
              mountPath: /docker-entrypoint-initdb.d/init.sql
              subPath: init.sql
              readOnly: true

          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - mariadb-admin ping -h 127.0.0.1 -u appUser -p"$MARIADB_PASSWORD"
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5

      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: db-data
        - name: db-cm1
          configMap:
            name: db-cm1
            items:
              - key: dbsetup.sql
                path: init.sql
